name: benford

channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7.9
    - numpy
    - scipy
    - pandas
    - xlrd # to read .xls files from Pandas
    - openpyxl # to read .xlsx files from Pandas
    - matplotlib
    - jupyterlab>=3
    - pycodestyle
    - pylint
    - pydocstyle
    - pytest
    - pytest-cov
    - pytest-mlp